---
title: "DATA_621_Final_Project"
author: "Chi Pong, Euclid Zhang, Jie Zou, Joseph Connolly, LeTicia Cancel"
date: "4/19/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library("stringr")
library("dplyr")
library("tidyr")

library("arm")
library("pROC")
library("car")
library("caret")
```


Note:

1. No user is using multiple device.
2. Users stay in the same location.
3. All songs are finished before going to the next song.
4. There is no remove from Playlist record.




```{r}
df <- read.csv("sparkify-medium.csv", stringsAsFactors = FALSE, row.names=1)
```



```{r}
regist_df <- filter(df,df$page=="Submit Registration")

for (i in c(1:nrow(regist_df))) {
  temp_df <- df %>% 
                filter(sessionId==regist_df$sessionId[i]) %>%
                filter(!is.na(userId)) %>% 
                mutate(delta=abs(ts-regist_df$ts[i])) %>% 
                arrange(delta,desc=FALSE)

  df[!is.na(df$userId) & df$userId==temp_df$userId[1],"registration"] <- regist_df$ts[i]
}
```

```{r}
df <- filter(df,!is.na(userId))
```


```{r}
df$userAgent[str_detect(df$userAgent,"Macintosh")] <- "Macintosh"
df$userAgent[str_detect(df$userAgent,"iPad")] <- "iPad"
df$userAgent[str_detect(df$userAgent,"iPhone")] <- "iPhone"
df$userAgent[str_detect(df$userAgent,"Windows")] <- "Windows"
df$userAgent[str_detect(df$userAgent,"Linux")] <- "Linux"
```

```{r}
selected_pages <- c("NextSong","Roll Advert","Add Friend","Thumbs Up",
                    "Add to Playlist", "Upgrade", "Submit Upgrade", "Error",
                    "Thumbs Down","Cancel", "Cancellation Confirmation",
                    "Downgrade", "Submit Downgrade","Submit Registration")
df <- df[df$page %in% selected_pages,]
```


```{r}
factor_columns <- c("page","auth","method","status","level","gender","userAgent")

df[factor_columns] <- lapply(df[factor_columns], factor)
```

```{r}
df$home <- NULL
df$method <- NULL
df$status <- NULL
df$itemInSession <- NULL
df$location <- NULL
df$lastName <- NULL
df$firstName <- NULL
```


```{r}
df <- arrange(df, ts,desc=FALSE)
head(df)
```

```{r}
df$user_song <- paste0(df$userId, df$artist, df$song)
temp <- df %>% group_by(user_song) %>% mutate(count=row_number())
df$new_song <- temp$count
temp <- NULL
df$user_song <- NULL
df$new_song[df$new_song > 1] <- 0
df$new_song[is.na(df$song)] <- NA
```

```{r}
df$ts <- df$ts/1000
df$registration <- df$registration/1000
df$week_reg <- 0

begin_ts <- 1538352000
end_ts <- 1543795199

for (ts in seq(begin_ts, end_ts, 604800)) {
  temp <- between(df$ts,ts,ts+604799)
  df$week_begins[temp] <- as.Date(as.POSIXct(ts, origin="1970-01-01"))
  df$week_reg[between(df$registration,ts,ts+604799) & temp] <- 1
}
df$week_begins <- as.Date(df$week_begins,origin="1970-01-01")
```


```{r}
df$date <- as.Date(as.POSIXct(df$ts, origin="1970-01-01"))
df$registration <- as.Date(as.POSIXct(df$registration, origin="1970-01-01"))
```



```{r}
df$weeks_since_reg <- as.numeric(floor((df$week_begins-df$registration)/7)) 
```

```{r}
df$weeks_since_reg[df$weeks_since_reg<0] <- 0
```


```{r}
summary(df)
```

```{r}
df2 <- df
```

```{r}
df2$auth <- NULL

summary(df2)
```


```{r}
page_df <- df2 %>% group_by(userId,week_begins) %>% 
  count(page) %>% 
  spread(page, n, fill = 0)
page_df$NextSong <- NULL
page_df$Cancel <- NULL
```


```{r message=FALSE, warning=FALSE}
user_df <- df2 %>% filter(!is.na(song)) %>% 
  arrange(ts, desc=FALSE) %>% 
  group_by(userId,week_begins) %>% 
  summarise(active_sessions=n_distinct(sessionId),
            active_days=n_distinct(date),
            songs_listened=n(),
            new_songs_listened=sum(new_song),
            weeks_since_reg=first(weeks_since_reg),
            start_level=first(level),
            end_level=last(level),
            gender=first(gender),
            userAgent=first(userAgent),
            week_reg=first(week_reg),
            last_active=last(ts))
```
```{r}
prepared_df <- merge(user_df, page_df, by=c("userId","week_begins")) %>% 
                arrange(userId, week_begins)
```



```{r}
obs_df <- data.frame(userId=unique(prepared_df$userId))
obs_df$start <- as.Date(as.POSIXct(1538352000, origin="1970-01-01"))
obs_df$end <- as.Date(as.POSIXct(1543190400, origin="1970-01-01"))
temp <- prepared_df[prepared_df$week_reg == 1,c("userId","week_begins")]
obs_df$start[obs_df$userId %in% temp$userId] <- temp$week_begins
temp <-prepared_df[prepared_df$`Cancellation Confirmation` == 1,c("userId","week_begins")]
obs_df$end[obs_df$userId %in% temp$userId] <- temp$week_begins

obs_df
```
```{r}
all_period_df <- data.frame(userId=NA, week_begins=NA)

cursor <- 1
for (i in c(1:nrow(obs_df))) {
    for (date in seq(obs_df$start[i], obs_df$end[i], 7)) {
        all_period_df[cursor,] <- c(obs_df$userId[i], as.Date(date, origin="1970-01-01"))
         cursor = cursor + 1
    }
}

all_period_df$userId <- as.integer(all_period_df$userId)
all_period_df$week_begins <- as.Date(all_period_df$week_begins, origin="1970-01-01")

all_period_df
```
```{r}

prepared_df <- merge(all_period_df, prepared_df, by=c("userId","week_begins"), all.x = TRUE)

```


```{r}
prepared_df
```


```{r}
prepared_df<- prepared_df %>% 
  group_by(userId) %>%
  fill(end_level,.direction = "down") %>% 
  fill(gender,.direction = "updown") %>% 
  fill(userAgent,.direction = "updown") %>% 
  fill(start_level,.direction = "up")
```
```{r}
prepared_df$end_level[is.na(prepared_df$end_level)]<-prepared_df$start_level[is.na(prepared_df$end_level)]
prepared_df$start_level <- NULL
prepared_df
```
```{r}
prepared_df$last_active[is.na(prepared_df$last_active) & prepared_df$week_begins == "2018-10-01"] <- 1538352000
prepared_df
```


```{r}
prepared_df <- prepared_df %>%
    group_by(userId) %>%
    fill(last_active,.direction = "down") %>% 
    mutate(last_active = dplyr::lag(last_active, n = 1, default = 1538352000))
```
```{r}
for (i in c(1:ncol(prepared_df))) {
  if (any(is.na(prepared_df[,i]))) {
    prepared_df[is.na(prepared_df[,i]),i] <- 0
  }
}
prepared_df
```

```{r}
prepared_df$inactive_days <- round((as.numeric(as.POSIXct(prepared_df$week_begins)) - prepared_df$last_active)/(3600*24),2)
prepared_df$last_active <- NULL
```

```{r}
prepared_df
```



```{r}
one_week_active <- prepared_df %>% group_by(userId) %>% 
  summarise(activate_weeks=n()) %>% 
  filter(activate_weeks==1)

filter(prepared_df, userId %in% one_week_active$userId)
```































